name: Wiki Sync to Pages

on:
  gollum:
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: temp-wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync wiki content
        run: |
          mkdir -p wiki

          for file in temp-wiki/*.md; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              if [[ "$filename" != "_"* ]]; then
                content=$(cat "$file")
                
                # Check if file starts with frontmatter
                if [[ $(head -n 1 "$file") == "---" ]]; then
                  # Has frontmatter, copy as-is
                  cp "$file" "wiki/$(basename $file)"
                else
                  # Look for first H1 heading
                  if h1_title=$(echo "$content" | grep -m 1 "^# "); then
                    title=$(echo "$h1_title" | sed 's/^# //')
                    echo -e "---\ntitle: ${title}\nlayout: default\n---\n\n$content" > "wiki/$(basename $file)"
                  else
                    # No H1, just copy the file as-is
                    cp "$file" "wiki/$(basename $file)"
                  fi
                fi
              fi
            fi
          done

          # Clean up
          rm -rf temp-wiki

          # Configure git with token-based authentication
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          # Commit and push changes if any
          git add wiki-content
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync wiki content"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
