name: Wiki Sync to Pages

on:
  gollum:
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is important to allow pushing

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Add this line
        
      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: temp-wiki
          token: ${{ secrets.GITHUB_TOKEN }}  # Add this line

      - name: Sync wiki content
        run: |
          # Create wiki content directory if it doesn't exist
          mkdir -p wiki-content

          # Copy and process markdown files
          for file in temp-wiki/*.md; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              if [[ "$filename" != "_"* ]]; then
                title=$(head -n 1 "$file" | sed 's/^#\s*//' || basename "$file" .md)
                
                if ! grep -q "^---" "$file"; then
                  echo -e "---\ntitle: ${title}\nlayout: wiki-page\n---\n\n$(cat $file)" > "wiki-content/$(basename $file)"
                else
                  cp "$file" "wiki-content/$(basename $file)"
                fi
              fi
            fi
          done

          # Clean up
          rm -rf temp-wiki

          # Configure git with token-based authentication
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          # Commit and push changes if any
          git add wiki-content
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync wiki content"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
